### ISSUE TITLE
Open mode "rB", should be "rb"

### ISSUE THREAD

**Issue by lrq3000** [JRBANCEL/Chromagnon#3]
Hey there,

Let me first say that it's a great project you've done here, and currently the only working solution to recover tabs from a crashed Chrome.

I've noticed a bug when trying to use the scripts:

```
Traceback (most recent call last):
  File "chromagnonTab.py", line 42, in <module>
    main()
  File "chromagnonTab.py", line 36, in main
    snss = chromagnon.SNSSParse.parse(sys.argv[1])
  File "C:\Users\LRQ\Downloads\Chromagnon-SNSS\Chromagnon-SNSS\chromagnon\SNSSPa
rse.py", line 46, in parse
    f = open(path, 'rB')
ValueError: Invalid mode ('rB')
```

The fix is to simply change `f = open(path, 'rB')` to `f = open(path, 'rb')`, then it works flawlessly on Python 2.7.10 (tested on Windows).

Side note: there are only two other projects trying to recover SNSS data (they work less well but the documentation may be interesting to you):

https://code.google.com/p/ccl-ssns/
https://github.com/lsauer/chrome-session-restore

The docs:

http://www.cclgroupltd.com/chrome-session-and-tabs-files-and-the-puzzle-of-the-pickle/
http://www.lsauer.com/2011/10/google-chrome-session-restore-web.html

**Comment by JRBANCEL** [comment]
Thanks @lrq3000 for reporting this issue. I never had the occasion to test my code on Windows.
I have no idea why I used 'rB' instead of 'rb', but it works on Linux and FreeBSD.
I didn't find anything in the documentation related to 'B'.
It has been fixed in d1c83b23224da34a6d2e111e82ec70ba21d90cd0.
I tested it on Windows 8.1.
